from github import Github, GithubIntegration
from app.config import settings

class GitHubService:
    def __init__(self):
        self.app_id = settings.GITHUB_APP_ID
        self.private_key = settings.GITHUB_PRIVATE_KEY

    def get_installation_client(self, installation_id: int):
        integration = GithubIntegration(self.app_id, self.private_key)
        access_token = integration.get_access_token(installation_id).token
        return Github(access_token)

    def create_pr(self, installation_id: int, repo_full_name: str,
                  file_path: str, new_content: str, commit_msg: str) -> str:
        client = self.get_installation_client(int(installation_id))
        repo = client.get_repo(repo_full_name)
        default_branch = repo.default_branch
        sha = repo.get_branch(default_branch).commit.sha

        import time
        branch_name = f"autofix/remediation-{int(time.time())}"
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sha)

        contents = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            path=file_path,
            message=commit_msg,
            content=new_content,
            sha=contents.sha,
            branch=branch_name
        )

        pr = repo.create_pull(
            title=f"[AutoFix-Ops] Remediate {file_path}",
            body="Automated security vulnerability fix generated by AutoFix-Ops.",
            head=branch_name,
            base=default_branch
        )
        return pr.html_url